# Generated by Django 2.1 on 2021-01-19 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.CharField(blank=True, max_length=25, null=True)),
                ('cantidadMin', models.IntegerField(default=2)),
                ('cantidadMax', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
            },
        ),
        migrations.CreateModel(
            name='BodegaMaiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipoMovimiento', models.CharField(max_length=25)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stockMaiz', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='CompraMaiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCompra', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('observacion', models.CharField(max_length=100)),
                ('humedad', models.IntegerField()),
                ('impureza', models.IntegerField()),
                ('valida', models.BooleanField(default=True)),
                ('pendiente', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDocumento', models.CharField(max_length=25)),
                ('numeroDocumento', models.IntegerField()),
                ('fechaEmision', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=7)),
                ('preciounitario', models.DecimalField(decimal_places=2, max_digits=4)),
                ('precioTotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(max_length=25)),
                ('tipoPago', models.CharField(max_length=25)),
                ('idCompraMaiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CompraMaiz')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=13, unique=True)),
                ('razonSocial', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Productor',
                'verbose_name_plural': 'Productores',
                'ordering': ['razonSocial'],
            },
        ),
        migrations.CreateModel(
            name='FacturaTransporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerofactura', models.IntegerField()),
                ('fechaFactura', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=7)),
                ('preciounitario', models.DecimalField(decimal_places=2, max_digits=4)),
                ('precioTotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(max_length=25)),
                ('tipoPago', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroFactura', models.IntegerField(unique=True)),
                ('fechaEmision', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=7)),
                ('preciounitario', models.DecimalField(decimal_places=2, max_digits=4)),
                ('precioTotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(max_length=25)),
                ('tipoPago', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField(default=1)),
                ('estado', models.CharField(blank=True, max_length=25, null=True)),
                ('cantidadMin', models.IntegerField(default=2)),
                ('cantidadMax', models.IntegerField(default=10)),
                ('unidadMedida', models.CharField(choices=[('Pieza', 'Pieza'), ('Metro', 'Metro'), ('Litro', 'Litro'), ('Galón', 'Galón'), ('Caneca', 'Caneca'), ('Libra', 'Libra'), ('kilogramo', 'Kilogramo'), ('Quintal', 'Quintal')], max_length=100)),
                ('fechaIngreso', models.DateField(auto_now=True)),
                ('stock', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='OrdenUso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('unidadMedida', models.CharField(max_length=25)),
                ('fechaSalida', models.DateField()),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Empleado')),
                ('idInventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inventario')),
            ],
        ),
        migrations.CreateModel(
            name='PesajeCompraMaiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPesaje', models.DateTimeField()),
                ('pesoBruto', models.IntegerField()),
                ('pesoTara', models.IntegerField()),
                ('pesoNeto', models.IntegerField()),
                ('factorConversion', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pesoQuintales', models.DecimalField(decimal_places=2, max_digits=7)),
                ('vigente', models.BooleanField(default=True)),
                ('idCompraMaiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CompraMaiz')),
            ],
        ),
        migrations.CreateModel(
            name='PesajeVentaMaiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPesaje', models.DateField()),
                ('pesoBruto', models.IntegerField()),
                ('pesoTara', models.IntegerField()),
                ('pesoNeto', models.IntegerField()),
                ('factorConversion', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pesoQuintales', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Productor',
                'verbose_name_plural': 'Productores',
                'ordering': ['nombres'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=13, unique=True)),
                ('razonSocial', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='ResponsableTransporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
                ('placaTrailer', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='VentaMaiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaVenta', models.DateField()),
                ('observaciones', models.CharField(max_length=100)),
                ('humedad', models.DecimalField(decimal_places=2, max_digits=4)),
                ('impureza', models.DecimalField(decimal_places=2, max_digits=3)),
                ('idBodegaMaiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.BodegaMaiz')),
                ('idEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Empresa')),
                ('idResponsableTransporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ResponsableTransporte')),
            ],
        ),
        migrations.AddField(
            model_name='pesajeventamaiz',
            name='idVentaMaiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.VentaMaiz'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='idProveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Proveedor'),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='idVentaMaiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.VentaMaiz'),
        ),
        migrations.AddField(
            model_name='facturatransporte',
            name='idVentaMaiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.VentaMaiz'),
        ),
        migrations.AddField(
            model_name='compramaiz',
            name='idProductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Productor'),
        ),
        migrations.AddField(
            model_name='bodegamaiz',
            name='idCompraMaiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CompraMaiz'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='idProveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Proveedor'),
        ),
    ]
