# Generated by Django 2.1 on 2021-03-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_compramaiz_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsabletransporte',
            options={'ordering': ['nombre'], 'verbose_name': 'Responsable Transporte', 'verbose_name_plural': 'Responsables Transporte'},
        ),
        migrations.AlterModelOptions(
            name='ventamaiz',
            options={'ordering': ['-pk']},
        ),
        migrations.RemoveField(
            model_name='ventamaiz',
            name='idBodegaMaiz',
        ),
        migrations.AddField(
            model_name='pesajeventamaiz',
            name='vigente',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ventamaiz',
            name='fechaModificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ventamaiz',
            name='pendiente',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ventamaiz',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventamaiz',
            name='valida',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ventamaiz',
            name='fechaVenta',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ventamaiz',
            name='humedad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ventamaiz',
            name='impureza',
            field=models.IntegerField(),
        ),
    ]
