# Generated by Django 2.1 on 2021-04-08 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210301_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True)),
                ('stock', models.IntegerField()),
                ('estado', models.CharField(blank=True, max_length=25, null=True)),
                ('unidadMedida', models.CharField(choices=[('Pieza', 'Pieza'), ('Metro', 'Metro'), ('Litro', 'Litro'), ('Galón', 'Galón'), ('Caneca', 'Caneca'), ('Libra', 'Libra'), ('kilogramo', 'Kilogramo'), ('Quintal', 'Quintal')], max_length=100)),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='ordenuso',
            name='idEmpleado',
        ),
        migrations.RemoveField(
            model_name='ordenuso',
            name='idInventario',
        ),
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['descripcion'], 'verbose_name': 'Articulo', 'verbose_name_plural': 'Articulos'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['razonSocial'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='pesajecompramaiz',
            options={'ordering': ['fechaPesaje'], 'verbose_name': 'PesajeCompraMaiz', 'verbose_name_plural': 'PesajeCompraMaiz'},
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='cantidadMax',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='cantidadMin',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='idProveedor',
        ),
        migrations.AddField(
            model_name='articulo',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulo',
            name='unidadMedida',
            field=models.CharField(choices=[('Pieza', 'Pieza'), ('Metro', 'Metro'), ('Litro', 'Litro'), ('Galón', 'Galón'), ('Caneca', 'Caneca'), ('Libra', 'Libra'), ('kilogramo', 'Kilogramo'), ('Quintal', 'Quintal')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentocompra',
            name='idProductor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Productor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articulo',
            name='descripcion',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='OrdenUso',
        ),
        migrations.AddField(
            model_name='articulos',
            name='idCategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Categoria'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='idCategoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Categoria'),
            preserve_default=False,
        ),
    ]
