# Generated by Django 2.1 on 2021-04-14 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210408_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoArticulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('idArticulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Articulo')),
                ('idProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Proveedor')),
            ],
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='idCategoria',
        ),
        migrations.DeleteModel(
            name='Articulos',
        ),
    ]
