# Generated by Django 2.1 on 2021-04-15 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210414_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalidaArticulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('idArticulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Articulo')),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Empleado')),
            ],
        ),
    ]
