# Generated by Django 2.1 on 2021-04-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_salidaarticulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
    ]
