# Generated by Django 2.1 on 2021-04-17 19:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210415_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleIngresoArticulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='ingresoarticulo',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='ingresoarticulo',
            name='idArticulo',
        ),
        migrations.AddField(
            model_name='ingresoarticulo',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='detalleingresoarticulos',
            name='idArticulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Articulo'),
        ),
        migrations.AddField(
            model_name='detalleingresoarticulos',
            name='idIngreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.IngresoArticulo'),
        ),
    ]
