# Generated by Django 2.1 on 2021-04-18 00:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210417_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleSalidaArticulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('idArticulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Articulo')),
            ],
        ),
        migrations.RemoveField(
            model_name='salidaarticulo',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='salidaarticulo',
            name='idArticulo',
        ),
        migrations.AlterField(
            model_name='salidaarticulo',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='detallesalidaarticulos',
            name='idSalida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SalidaArticulo'),
        ),
    ]
