# Generated by Django 2.1 on 2021-04-25 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210418_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentocompra',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='documentocompra',
            name='idCompraMaiz',
        ),
        migrations.AddField(
            model_name='compramaiz',
            name='idDocumentoCompra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.DocumentoCompra'),
        ),
    ]
