# Generated by Django 2.1 on 2021-05-03 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210425_2246'),
        ('app', '0010_auto_20210501_1458'),
    ]

    operations = [
    ]
