# Generated by Django 2.1 on 2021-05-05 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210504_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pesajeventamaiz',
            options={'ordering': ['fechaPesaje'], 'verbose_name': 'PesajeVentaMaiz', 'verbose_name_plural': 'PesajeVentaMaiz'},
        ),
        migrations.RemoveField(
            model_name='facturaventa',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='facturaventa',
            name='idVentaMaiz',
        ),
        migrations.RemoveField(
            model_name='facturaventa',
            name='tipoPago',
        ),
        migrations.AddField(
            model_name='ventamaiz',
            name='idFacturaVenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FacturaVenta'),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='numeroFactura',
            field=models.CharField(max_length=12),
        ),
    ]
