# Generated by Django 2.1 on 2021-05-06 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210505_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturatransporte',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='facturatransporte',
            name='idVentaMaiz',
        ),
        migrations.RemoveField(
            model_name='facturatransporte',
            name='tipoPago',
        ),
        migrations.AddField(
            model_name='ventamaiz',
            name='idFacturaTransporte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FacturaTransporte'),
        ),
        migrations.AddField(
            model_name='ventamaiz',
            name='statusFactura',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='facturatransporte',
            name='numerofactura',
            field=models.CharField(max_length=12),
        ),
    ]
