# Generated by Django 2.1 on 2021-05-08 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210506_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturaventa',
            options={'ordering': ['fechaEmision'], 'verbose_name': 'facturaVenta', 'verbose_name_plural': 'facturasVenta'},
        ),
        migrations.AddField(
            model_name='facturatransporte',
            name='idVentaMaiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.VentaMaiz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='idVentaMaiz',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.VentaMaiz'),
            preserve_default=False,
        ),
    ]
