# Generated by Django 2.1 on 2021-05-08 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210508_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturatransporte',
            name='idVentaMaiz',
        ),
        migrations.RemoveField(
            model_name='facturaventa',
            name='idVentaMaiz',
        ),
        migrations.AddField(
            model_name='facturatransporte',
            name='idEmpresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='idEmpresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Empresa'),
            preserve_default=False,
        ),
    ]
