# Generated by Django 2.1 on 2021-05-09 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210508_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturatransporte',
            old_name='fechaFactura',
            new_name='fechaEmision',
        ),
        migrations.RemoveField(
            model_name='facturatransporte',
            name='idEmpresa',
        ),
        migrations.AddField(
            model_name='facturatransporte',
            name='idResponsableTransporte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.ResponsableTransporte'),
            preserve_default=False,
        ),
    ]
